using System;
using System.Collections.Generic;

#nullable disable

namespace CourseManagementAPI.AutoGeneratedModel
{
    public partial class Account
    {
        public Account()
        {
            TransactionAccountNumberNavigations = new HashSet<Transaction>();
            TransactionDestinationAccountNumberNavigations = new HashSet<Transaction>();
        }

        public int AccountNumber { get; set; }
        public string AccountType { get; set; }
        public int CustomerId { get; set; }
        public decimal Balance { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual ICollection<Transaction> TransactionAccountNumberNavigations { get; set; }
        public virtual ICollection<Transaction> TransactionDestinationAccountNumberNavigations { get; set; }
    }
}
